version: '3'

networks:
    messages_app:

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: "messages_app_php"
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - messages_app
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
    nginx:
        image: nginx:stable-alpine
        container_name: "messages_app_nginx"
        ports:
            - "8091:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - messages_app
    mysql:
        image: mysql:8.0.29
        container_name: "messages_app_mysql"
        restart: unless-stopped
        tty: true
        ports:
            - 8306:3306
        volumes:
            - messages_app-volume:/var/lib/mysql
            - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - messages_app
volumes:
    messages_app-volume:


